package com.briup.apps.briupej.service;

import com.briup.apps.briupej.bean.OrderLine;
import com.briup.apps.briupej.bean.OrderLineExample;
import com.briup.apps.briupej.bean.extend.OrderLine_Extend;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderLineService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    long countByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByPrimaryKey(Long id) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insert(OrderLine record) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insertSelective(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    List<OrderLine> selectByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    //Order_line selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderLine record, @Param("example") OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExample(@Param("record") OrderLine record, @Param("example") OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKeySelective(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order_line
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKey(OrderLine record) throws Exception;


    //查询订单项通过id
    OrderLine_Extend findAllOrder_lineById(Long id);

    //查询所有的订单项
    List<OrderLine_Extend> findAllOrder_line();

    void betchDelete(long[] ids) throws Exception;
}

